// <auto-generated />
using System;
using Locadora.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Locadora.Infrastructure.Migrations
{
    [DbContext(typeof(LocadoraDbContext))]
    [Migration("20260127114327_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Locadora.Infrastructure.Persistence.Entities.ClienteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Cnh")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cnh");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime")
                        .HasColumnName("criado_em");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nome");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("responsavel");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Locadora.Infrastructure.Persistence.Entities.LocacaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("char(36)")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("Devolucao")
                        .HasColumnType("date")
                        .HasColumnName("devolucao");

                    b.Property<DateOnly>("Prevista")
                        .HasColumnType("date")
                        .HasColumnName("prevista");

                    b.Property<DateOnly>("Retirada")
                        .HasColumnType("date")
                        .HasColumnName("retirada");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal?>("ValorFinal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_final");

                    b.Property<decimal>("ValorPrevisto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_previsto");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Status")
                        .HasDatabaseName("ix_locacoes_cliente_status");

                    b.HasIndex("VeiculoId", "Status")
                        .HasDatabaseName("ix_locacoes_veiculo_status");

                    b.ToTable("locacoes", (string)null);
                });

            modelBuilder.Entity("Locadora.Infrastructure.Persistence.Entities.LocacaoExtraEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("LocacaoId")
                        .HasColumnType("char(36)")
                        .HasColumnName("locacao_id");

                    b.Property<decimal>("PrecoPorDia")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_por_dia");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<string>("TipoExtra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_extra");

                    b.HasKey("Id");

                    b.HasIndex("LocacaoId")
                        .HasDatabaseName("ix_locacao_extras_locacao");

                    b.ToTable("locacao_extras", (string)null);
                });

            modelBuilder.Entity("Locadora.Infrastructure.Persistence.Entities.VeiculoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("ano");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("disponivel");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("placa");

                    b.Property<decimal>("ValorDiaria")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_diaria");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("veiculos", (string)null);
                });

            modelBuilder.Entity("Locadora.Infrastructure.Persistence.Entities.LocacaoEntity", b =>
                {
                    b.HasOne("Locadora.Infrastructure.Persistence.Entities.ClienteEntity", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Locadora.Infrastructure.Persistence.Entities.VeiculoEntity", "Veiculo")
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Locadora.Infrastructure.Persistence.Entities.LocacaoExtraEntity", b =>
                {
                    b.HasOne("Locadora.Infrastructure.Persistence.Entities.LocacaoEntity", "Locacao")
                        .WithMany("Extras")
                        .HasForeignKey("LocacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locacao");
                });

            modelBuilder.Entity("Locadora.Infrastructure.Persistence.Entities.LocacaoEntity", b =>
                {
                    b.Navigation("Extras");
                });
#pragma warning restore 612, 618
        }
    }
}
